<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Payment.Domain\Payment.Domain.csproj" />
    <ProjectReference Include="..\Payment.Contracts\Payment.Contracts.csproj" />
  </ItemGroup>

</Project>
