<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Exploration.Domain\Exploration.Domain.csproj" />
    <ProjectReference Include="..\Exploration.Contracts\Exploration.Contracts.csproj" />
  </ItemGroup>

</Project>
