<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Payment.Application\Payment.Application.csproj" />
    <ProjectReference Include="..\Payment.Domain\Payment.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.Infrastructure\Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Payment.Tests" />
  </ItemGroup>

</Project>
