// <auto-generated />
using System;
using System.Collections.Generic;
using Exploration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Exploration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExplorationDbContext))]
    [Migration("20260827103224_InitialExploration")]
    partial class InitialExploration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("exploration")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exploration.Domain.Tours.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Tours", "exploration");
                });

            modelBuilder.Entity("Exploration.Domain.Tours.Tour", b =>
                {
                    b.OwnsMany("Exploration.Domain.Tours.TransportTime", "TransportTimes", b1 =>
                        {
                            b1.Property<Guid>("TourId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Minutes");

                            b1.Property<string>("Transport")
                                .IsRequired();

                            b1.HasKey("TourId", "__synthesizedOrdinal");

                            b1.ToTable("Tours", "exploration");

                            b1
                                .ToJson("TransportTimes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TourId");
                        });

                    b.Navigation("TransportTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
