<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Games.Application\Games.Application.csproj" />
    <ProjectReference Include="..\Games.Domain\Games.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.Infrastructure\Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Games.Tests" />
  </ItemGroup>

</Project>
